---
# tasks file for kind_create_cluster
- name: Run kind command
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command:
    cmd: >
      kind create cluster --name istio-testing
        --config ../manifests/kind/kind-config.yaml

- name: "[Debug] print kind command result"
  ansible.builtin.debug:
    msg: "{{ my_output }}"

- name: Deploy Prom stack
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command:
    cmd: >
      helm install -n monitoring --create-namespace
        -f ../values/prometheus-stack.yaml
        kube-prometheus-stack
        prometheus-community/kube-prometheus-stack

- name: Deploy Istio objects
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command:
    cmd: >
      helm install istio-base istio/base -n istio-system --set defaultRevision=default --create-namespace


- name: Deploy IstioD objects
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command:
    cmd: >
      helm install istiod istio/istiod -n istio-system --wait

- name: Create ingress namespace
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command:
    cmd: >
      kubectl create namespace istio-ingress

- name: Deploy Istio Gateway Controller
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command:
    cmd: >
      helm install -f ../values/gateway.yaml istio-ingressgateway istio/gateway -n istio-ingress

- name: Deploy Istio Gateway
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command:
    cmd: >
      kubectl apply -f ../manifests/gateway/istio-gateway.yaml -n istio-ingress

- name: Deploy Prom services
  register: my_output
  changed_when: my_output.rc != 0
  ansible.builtin.command:
    cmd: >
      helm upgrade --install -n monitoring prom-stack-service ../charts/prom-stack-service

# - name: Run kind command
#   register: my_output
#   changed_when: my_output.rc != 0
#   ansible.builtin.command: "kind delete clusters istio-testing"
