# Default values for kiali-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

gateway: istio-ingress/istio-ingress-gateway

hosts:
- kiali.mainframe.local
service:
  name: kiali
  port: 20001
  selectorLabels:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/version: v2.5.0