---

- name: "[Debug] Is WSL"
  when: wsl
  ansible.builtin.debug:
    msg: "System is WSL"

- name: "[Debug] Print .wslconfig"
  when: wsl
  register: file_content
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.file', '/mnt/c/Users/maxim/.wslconfig') }}"

- name: "[Debug] Templating"
  when: wsl
  ansible.builtin.template:
    src: templates/.wslconfig.j2
    dest: '/mnt/c/Users/maxim/.wslconfig.tmp'
    newline_sequence: "\\r\\n"
    mode: "0777"

- name: "[Debug] Print .wslconfig.tmp"
  when: wsl
  register: tmp_content
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.file', '/mnt/c/Users/maxim/.wslconfig.tmp') }}"

- name: "[Debug] If file_content == tmp_content"
  when: wsl and (file_content == tmp_content)
  ansible.builtin.debug:
    msg: "Do nothing except cleanup .tmp file"

- name: "[Debug] Remove file .tmp file"
  when: wsl
  ansible.builtin.file:
    path: '/mnt/c/Users/maxim/.wslconfig.tmp'
    state: absent

- name: "[Debug] Update WSL resources"
  when: wsl and not (file_content == tmp_content)
  ansible.builtin.template:
    src: templates/.wslconfig.j2
    dest: '/mnt/c/Users/maxim/.wslconfig'
    newline_sequence: "\\r\\n"
    mode: "0777"

- name: "[Debug] Restart Docker Desktop"
  when: wsl and not (file_content == tmp_content)
  ansible.builtin.debug:
    msg: "Should restart Docker Desktop"
