apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "prom-stack-service.fullname-prometheus" . }}
  labels:
    {{- include "prom-stack-service.labels-prometheus" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.prometheus.hosts }}
  - {{ . }}
  {{- end }}
  gateways:
  - {{ .Values.gateway }}
  http:
  - name: "all-routes"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ .Values.prometheus.service.name }}
        subsets: {{ include "prom-stack-service.fullname-prometheus" . }}
        port: 
          number: {{ .Values.prometheus.service.port | int }}